/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTables;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

  @Test void testHashTableAddingKeyValue() {
    HashTable<String, Integer> test = new HashTable<>();
    test.add("bayan",3);
    boolean output = test.contains("bayan");
    assertTrue(output);
  }

  @Test void testRetrievingAddedValue(){
    HashTable<String, Integer> test = new HashTable<>();
    test.add("bayan",3);
    int output = test.get("bayan");
    assertEquals(output, 3);
  }

  @Test void testReturnNull(){
    HashTable<String, Integer> test = new HashTable<>();
    Integer output = test.get("bayan");
    assertNull(output);
  }

}
