/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  Node a = new Node(1);
  Node b = new Node(2);
  Node c = new Node(3);
  Node d = new Node(4);
  Node e = new Node(5);
  Node f = new Node(6);


  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }

  @Test
  void instantiateBinarySearchTree() {
    BinarySearchTree<Integer> bst = new BinarySearchTree<>();
    assertNotNull(bst);
  }

  @Test
  void rootBinarySearchTree() {
    BinarySearchTree<Integer> bst = new BinarySearchTree<>();
    
    a.setLeft(b);
    a.setRight(c);
    b.setLeft(d);
    b.setRight(e);
    c.setLeft(f);
    bst.add(a, 7);
    System.out.println(bst.contain(a, 4));
    System.out.println(bst.root.getValue());
//    assertEquals("1", bst.preOrder(bst.root).toString());

  }
  @Test void emptyTreeInstantiation (){
    BinarySearchTree<Integer> bst = new BinarySearchTree<>();
    assertNotNull(bst);
  }
  @Test void oneRootTree(){
    BinarySearchTree<Integer> bst = new BinarySearchTree<>();
    bst.add(a, 10);
    assertEquals("10", bst.preOrder(bst.root).toString());
  }

}
