/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }

  @Test
  void instantiateBinarySearchTree() {
    BinarySearchTree<Integer> bst = new BinarySearchTree<>();
    assertNotNull(bst);
  }

  @Test
  void rootBinarySearchTree() {
    BinarySearchTree<Integer> bst = new BinarySearchTree<>();


    bst.add(1);
    bst.add(2);
//    bst.add(3);
//    bst.ad
//    d(4);
//    bst.add(5);
//    bst.contain(1);

    System.out.println(bst.getRoot().getValue());
    System.out.println(bst.root.getLeft());
//    assertEquals("1", bst.preOrder(bst.root).toString());

  }
  @Test void emptyTreeInstantiation (){
    BinarySearchTree<Integer> bst = new BinarySearchTree<>();
    assertNotNull(bst);
  }
  @Test void oneRootTree(){
    BinarySearchTree<Integer> bst = new BinarySearchTree<>();
//    bst.add(a, 10);
    assertEquals("1", bst.preOrder(bst.root).toString());
  }

}
