/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.LinkedLists;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

      LinkedList linkedList = new LinkedList();
      linkedList.insert(5);
      linkedList.insert(20);
      System.out.println(linkedList.toString());
      linkedList.insert(14);
      linkedList.insert(9);
      System.out.println(linkedList.includes(14));
      System.out.println(linkedList.includes(17));
      System.out.println(linkedList.toString());
      linkedList.insertBefore(14,7);

      linkedList.append(72);
      linkedList.insertAfter(14,82);
      System.out.println(linkedList.toString());
      System.out.println(linkedList.head.value);
    }
}
