/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graphs;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

  @Test void graphArrayListTest() {
    Graph graph = new Graph();
    Node n1 = new Node("1");
    Node n2 = new Node("2");
    Node n3 = new Node("3");
    Node n4 = new Node("4");

    assertEquals("[]", graph.graphList.toString());
    graph.addNode(n1);
    assertTrue(graph.graphList.contains(n1));
    graph.addNode(n2);
    assertTrue(graph.graphList.contains(n2));
    graph.addNode(n3);
    graph.addNode(n4);

    assertEquals("[1, 2, 3, 4]", graph.toString());
    assertEquals(4, graph.size());
  }


}
