/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Android;

import org.junit.jupiter.api.Test;

import java.lang.reflect.Array;
import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void testInsertionSort(){

      Sort sort = new Sort();
      int[] array = {8, 4, 23, 42, 16, 15};
      int[] arraySorted = {4, 8, 15, 16, 23, 42};

      assertArrayEquals(sort.insertionSort(array), arraySorted );
    }

    @Test void testMergeSort(){
      Sort sort = new Sort();
      int[] array = {8, 4, 23, 42, 16, 15};
      int[] arraySorted = {4, 8, 15, 16, 23, 42};
      sort.mergeSort(array);
      assertArrayEquals(array,arraySorted);
    }
}
