/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Android;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void testInsertionSort(){

      InsertionSort sort = new InsertionSort();
      int[] array = {8, 4, 23, 42, 16, 15};
      int[] arraySorted = {4, 8, 15, 16, 23, 42};

      assertArrayEquals(sort.insertionSort(array), arraySorted );
    }
}
